# Generated by Django 2.1.3 on 2019-10-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='difusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Texto del mensaje')),
                ('archivo', models.FileField(upload_to='', verbose_name='Archivo')),
                ('adjunto', models.BooleanField(default=False)),
            ],
        ),
    ]
