# Generated by Django 2.1.3 on 2019-10-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsappBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difusion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='mensaje_libre', verbose_name='Archivo'),
        ),
    ]
