# Generated by Django 2.1.3 on 2019-10-21 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskHechas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=80, unique=True)),
                ('fechayhora', models.DateTimeField(default=datetime.datetime(2019, 10, 21, 8, 22, 4, 38783))),
            ],
        ),
    ]
