# Generated by Django 2.1.3 on 2019-10-21 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CeleryTasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytaskhechas',
            name='fechayhora',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 21, 9, 16, 29, 743839)),
        ),
    ]
